# Generated by Django 6.0.3 on 2026-04-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('rkap_target', models.DecimalField(decimal_places=2, max_digits=15)),
                ('realization', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pof_rate', models.FloatField(help_text='Perfect Order Fulfillment (%)')),
                ('ofct_days', models.IntegerField(help_text='Order Fulfillment Cycle Time (Hari)')),
                ('cogs_rate', models.FloatField(help_text='Cost of Goods Sold (%)')),
                ('is_synced_simbara', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
