# Generated by Django 6.0.3 on 2026-04-05 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coalperformance',
            name='created_at',
        ),
        migrations.AddField(
            model_name='coalperformance',
            name='gross_profit_rate',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='coalperformance',
            name='target_cogs',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='coalperformance',
            name='target_pof',
            field=models.FloatField(default=99.0),
        ),
        migrations.AddField(
            model_name='coalperformance',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=38490000000000, max_digits=20),
        ),
        migrations.AlterField(
            model_name='coalperformance',
            name='cogs_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coalperformance',
            name='ofct_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coalperformance',
            name='pof_rate',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='QualityClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('Quality', 'Kualitas'), ('Quantity', 'Kuantitas')], max_length=50)),
                ('description', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='claims/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='supply_chain.coalperformance')),
            ],
        ),
    ]
