# Generated by Django 6.0.3 on 2026-04-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_remove_coalperformance_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualityclaim',
            old_name='description',
            new_name='issue',
        ),
        migrations.RemoveField(
            model_name='coalperformance',
            name='target_cogs',
        ),
        migrations.RemoveField(
            model_name='qualityclaim',
            name='claim_type',
        ),
        migrations.AddField(
            model_name='coalperformance',
            name='simbara_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coalperformance',
            name='target_ofct',
            field=models.IntegerField(default=97),
        ),
        migrations.AddField(
            model_name='qualityclaim',
            name='customer',
            field=models.CharField(default='General Customer', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualityclaim',
            name='evidence_file',
            field=models.FileField(upload_to='claims/'),
        ),
    ]
