# Generated by Django 6.0.3 on 2026-04-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_rename_description_qualityclaim_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityclaim',
            name='claim_type',
            field=models.CharField(choices=[('Quality', 'Kualitas'), ('Quantity', 'Kuantitas')], default='Quality', max_length=50),
        ),
        migrations.AlterField(
            model_name='qualityclaim',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualityclaim',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='claims/'),
        ),
        migrations.AlterField(
            model_name='qualityclaim',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
